services:
  - type: web
    name: tracelink-spiderfoot
    env: docker
    imageUrl: docker.io/smgorven/spiderfoot:latest
    plan: free
    envVars:
      - key: PORT
        value: "5001"
      - key: SPIDERFOOT_HOST
        value: "0.0.0.0"
      - key: SPIDERFOOT_PORT
        value: "5001"
