services:
  - type: web
    name: tracelink-spiderfoot
    env: python
    repo: https://github.com/poppopjmp/spiderfoot
    branch: main
    buildCommand: "pip3 install -r requirements.txt"
    startCommand: "python3 sf.py -l 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: PORT
        value: "5001"
      - key: SPIDERFOOT_UI_PORT
        value: "5001"
      - key: SPIDERFOOT_PROFILE
        value: "scan"
